#!/usr/bin/env node
// Sync generated artifacts from the single source of truth (skills/*/SKILL.md).
//
// Generates:
//   commands/ppk-<name>.toml         (Gemini CLI / Codex command stubs)
//   plugins/prd-phase-kit/skills/**            (Claude Code plugin mirror)
//
// Usage:
//   node scripts/sync.js          # write artifacts
//   node scripts/sync.js --check  # fail (exit 1) if artifacts are out of date

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.join(ROOT, 'skills');
const COMMANDS_DIR = path.join(ROOT, 'commands');
const PLUGIN_SKILLS_DIR = path.join(ROOT, 'plugins', 'prd-phase-kit', 'skills');

const CHECK = process.argv.includes('--check');

const { loadSkills } = require('../bin/lib/skills.js');
const { shortDesc, tomlLiteral } = require('../bin/lib/providers.js');

function buildToml(skill) {
  const desc = shortDesc(skill.description);
  const prompt = skill.body + '\n\nFollow skills/_shared/conventions.md for the full rule set.';
  return (
    `# AUTO-GENERATED by scripts/sync.js from skills/${skill.name}/SKILL.md — do not edit.\n` +
    `description = ${JSON.stringify(desc)}\n` +
    `prompt = ${tomlLiteral(prompt)}\n`
  );
}

const planned = []; // { file, content }

for (const skill of loadSkills(ROOT)) {
  planned.push({
    file: path.join(COMMANDS_DIR, `${skill.command}.toml`),
    content: buildToml(skill),
  });

  // Mirror the whole skill directory into the Claude plugin distribution.
  const srcDir = path.join(SKILLS_DIR, skill.name);
  for (const entry of fs.readdirSync(srcDir)) {
    planned.push({
      file: path.join(PLUGIN_SKILLS_DIR, skill.name, entry),
      content: fs.readFileSync(path.join(srcDir, entry), 'utf8'),
    });
  }
}

// Mirror shared conventions too so plugin references resolve.
planned.push({
  file: path.join(PLUGIN_SKILLS_DIR, '_shared', 'conventions.md'),
  content: fs.readFileSync(path.join(SKILLS_DIR, '_shared', 'conventions.md'), 'utf8'),
});

let stale = 0;
for (const { file, content } of planned) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (current === content) continue;
  stale++;
  if (CHECK) {
    console.error(`out of date: ${path.relative(ROOT, file)}`);
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`wrote ${path.relative(ROOT, file)}`);
  }
}

if (CHECK && stale > 0) {
  console.error(`\n${stale} file(s) out of date. Run: npm run sync`);
  process.exit(1);
}
if (!CHECK) {
  console.log(stale === 0 ? 'already in sync' : `synced ${stale} file(s)`);
}