#!/usr/bin/env node
// Sync generated artifacts from the single source of truth (skills/*/SKILL.md).
//
// Generates:
//   commands/ppk-<name>.toml         (Gemini CLI / Codex command stubs)
//   plugins/prd-phase-kit/skills/**            (Claude Code plugin mirror)
//
// Usage:
//   node scripts/sync.js          # write artifacts
//   node scripts/sync.js --check  # fail (exit 1) if artifacts are out of date

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.join(ROOT, 'skills');
const COMMANDS_DIR = path.join(ROOT, 'commands');
const PLUGIN_SKILLS_DIR = path.join(ROOT, 'plugins', 'prd-phase-kit', 'skills');

const CHECK = process.argv.includes('--check');

/** List skill directories (each containing a SKILL.md), excluding shared. */
function listSkills() {
  return fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory() && d.name !== '_shared')
    .map((d) => d.name)
    .filter((name) => fs.existsSync(path.join(SKILLS_DIR, name, 'SKILL.md')))
    .sort();
}

/** Split a SKILL.md into { frontmatter, body }. */
function parseSkill(raw) {
  raw = raw.replace(/\r\n/g, '\n');
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { frontmatter: {}, body: raw.trim() };
  const fm = {};
  // Minimal YAML: only `key: value` and folded `key: >` blocks are needed here.
  const lines = m[1].split('\n');
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const kv = line.match(/^([a-zA-Z_][\w-]*):\s*(.*)$/);
    if (!kv) continue;
    const key = kv[1];
    let val = kv[2];
    if (val === '>' || val === '|') {
      const folded = [];
      while (i + 1 < lines.length && /^\s+/.test(lines[i + 1])) {
        folded.push(lines[++i].trim());
      }
      val = folded.join(' ');
    }
    fm[key] = val.trim();
  }
  return { frontmatter: fm, body: m[2].trim() };
}

/** First sentence of the description, for a short command summary. */
function shortDescription(desc, fallback) {
  if (!desc) return fallback;
  const firstSentence = desc.split(/(?<=[.!?])\s/)[0];
  return firstSentence.replace(/\s+/g, ' ').trim();
}

function tomlLiteral(value) {
  // TOML multi-line literal string: no escaping, must not contain '''.
  if (value.includes("'''")) {
    throw new Error("SKILL body contains ''' which breaks TOML literal strings");
  }
  return "'''\n" + value + "\n'''";
}

function buildToml(name, frontmatter, body) {
  const desc = shortDescription(frontmatter.description, `PRD Phase Kit ${name}`);
  const prompt = body + '\n\nFollow skills/_shared/conventions.md for the full rule set.';
  return (
    `# AUTO-GENERATED by scripts/sync.js from skills/${name}/SKILL.md — do not edit.\n` +
    `description = ${JSON.stringify(desc)}\n` +
    `prompt = ${tomlLiteral(prompt)}\n`
  );
}

const planned = []; // { file, content }

for (const name of listSkills()) {
  const skillPath = path.join(SKILLS_DIR, name, 'SKILL.md');
  const raw = fs.readFileSync(skillPath, 'utf8');
  const { frontmatter, body } = parseSkill(raw);

  planned.push({
    file: path.join(COMMANDS_DIR, `ppk-${name}.toml`),
    content: buildToml(name, frontmatter, body),
  });

  // Mirror the whole skill directory into the Claude plugin distribution.
  const srcDir = path.join(SKILLS_DIR, name);
  for (const entry of fs.readdirSync(srcDir)) {
    planned.push({
      file: path.join(PLUGIN_SKILLS_DIR, name, entry),
      content: fs.readFileSync(path.join(srcDir, entry), 'utf8'),
    });
  }
}

// Mirror shared conventions too so plugin references resolve.
planned.push({
  file: path.join(PLUGIN_SKILLS_DIR, '_shared', 'conventions.md'),
  content: fs.readFileSync(path.join(SKILLS_DIR, '_shared', 'conventions.md'), 'utf8'),
});

let stale = 0;
for (const { file, content } of planned) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
  if (current === content) continue;
  stale++;
  if (CHECK) {
    console.error(`out of date: ${path.relative(ROOT, file)}`);
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`wrote ${path.relative(ROOT, file)}`);
  }
}

if (CHECK && stale > 0) {
  console.error(`\n${stale} file(s) out of date. Run: npm run sync`);
  process.exit(1);
}
if (!CHECK) {
  console.log(stale === 0 ? 'already in sync' : `synced ${stale} file(s)`);
}